name: env
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - mystmd
  - jupyterlab-myst
  - numpy
  - matplotlib
  - seaborn
  - holoviews
  - pandas
  - erddapy
  - nodejs
  - tqdm
  - sklearn
